platform: linux

image_resource:
  type: registry-image
  source:
    repository: golang
    tag: 1.13

inputs:
  - name: oauth2_proxy
  - name: ci
  - name: version
    optional: true

outputs:
  - name: assets

caches:
  - path: gopath/

run:
  path: ci/ci/tasks/scripts/build.sh
