platform: linux

image_resource:
  type: registry-image
  source:
    repository: golang
    tag: 1.12

inputs:
  - name: ci
  - name: oauth2_proxy

caches:
  - path: gopath/

run:
  path: ci/ci/tasks/scripts/fast-tests.sh

